import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Footer, Footer2 } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <div className="flex justify-center gap-4">
          <div className="sm:hidden">
            <Footer/>
          </div>
        
          <div className="md:hidden">
            <Footer2/>
          </div>
        
        </div>
        </body>
    </html>
  );
}
